name: dart_code_metrics
version: 5.7.8
description: Software analytics tool that helps developers analyse and improve software quality.
homepage: https://dcm.dev/
repository: https://github.com/joaopedro735/dart-code-metrics
issue_tracker: https://github.com/dart-code-checker/dart-code-metrics/issues
documentation: https://dcm.dev/docs/getting-started/

environment:
  sdk: ">=2.18.0 <4.0.0"

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer: ">=5.12.0 <7.0.0"
  analyzer_plugin: "^0.11.3"
  ansicolor: ^2.0.2
  args: ^2.4.0
  collection: ^1.18.0
  crypto: ^3.0.3
  dart_code_metrics_presets: ^2.10.0
  file: ^7.0.0
  glob: ^2.1.2
  html: ">=0.15.0 <1.0.0"
  http: ^1.0.0
  meta: any
  path: ^1.8.0
  platform: ^3.1.0 # overridden for lowest versions compatibility
  pub_updater: ^0.4.0
  source_span: ^1.10.0
  uuid: ">=3.0.7 <5.0.0"
  xml: ">=5.3.0 <7.0.0"
  yaml: ^3.1.0

dev_dependencies:
  coverage: ^1.7.2
  intl: ^0.19.0
  lints: ^3.0.0
  mocktail: ^1.0.3
  test: ^1.21.0

  # internal package, used only in tests data
  test_lints:
    path: ./test/resources/test_lints

executables:
  metrics:
